# Should reside in input/drivers/rmi4
obj-$(CONFIG_RMI4_BUS) += rmi_bus.o
obj-$(CONFIG_RMI4_I2C) += rmi_i2c.o
obj-$(CONFIG_RMI4_SPI) += rmi_spi.o
obj-$(CONFIG_RMI4_GENERIC) += rmi_generic.o
rmi_generic-objs := rmi_driver.o rmi_f01.o
obj-$(CONFIG_RMI4_F11) += rmi_f11.o
